"""Creacion de tabla mascotas

Revision ID: 2f9aae97f526
Revises: b111ba914ffc
Create Date: 2023-07-28 15:25:06.932623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9aae97f526'
down_revision = 'b111ba914ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('PERRO', 'GATO', 'LORO', name='tipomascota'), nullable=False),
    sa.Column('sexo', sa.Enum('MACHO', 'HERMBRA', name='sexomascota'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('usuario.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario.id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    # ### end Alembic commands ###
