"""new

Revision ID: 991b7aafb4ec
Revises: 4c99dba8755f
Create Date: 2023-08-06 16:25:24.537200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '991b7aafb4ec'
down_revision = '4c99dba8755f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=postgresql.ENUM('MARKETING', 'SISTEMAS', 'CONTABILIDAD', name='tipoarea'),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('MARKETING', 'SISTEMAS', 'CONTABILIDAD', name='tipoarea'),
               existing_nullable=False)

    # ### end Alembic commands ###
